# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_diag.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(553, 266)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(190, 220, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.plainTextEdit_tl = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_tl.setGeometry(QtCore.QRect(110, 20, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.plainTextEdit_tl.setFont(font)
        self.plainTextEdit_tl.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_tl.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_tl.setPlainText("")
        self.plainTextEdit_tl.setObjectName("plainTextEdit_tl")
        self.plainTextEdit_au = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_au.setGeometry(QtCore.QRect(110, 70, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.plainTextEdit_au.setFont(font)
        self.plainTextEdit_au.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_au.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_au.setPlainText("")
        self.plainTextEdit_au.setObjectName("plainTextEdit_au")
        self.plainTextEdit_jn = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_jn.setGeometry(QtCore.QRect(110, 120, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.plainTextEdit_jn.setFont(font)
        self.plainTextEdit_jn.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_jn.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_jn.setPlainText("")
        self.plainTextEdit_jn.setObjectName("plainTextEdit_jn")
        self.plainTextEdit_url = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_url.setGeometry(QtCore.QRect(110, 170, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.plainTextEdit_url.setFont(font)
        self.plainTextEdit_url.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_url.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_url.setPlainText("")
        self.plainTextEdit_url.setObjectName("plainTextEdit_url")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 30, 54, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 54, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 54, 12))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 180, 54, 12))
        self.label_4.setObjectName("label_4")
        self.plainTextEdit_yr = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_yr.setGeometry(QtCore.QRect(370, 120, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.plainTextEdit_yr.setFont(font)
        self.plainTextEdit_yr.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_yr.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_yr.setPlainText("")
        self.plainTextEdit_yr.setObjectName("plainTextEdit_yr")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 230, 54, 12))
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(110, 220, 75, 31))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #ffcccc;\n"
"    color: black;\n"
"    border: 1px solid #a0a0a0;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #e9bbbb;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #e1b4b4;\n"
"}\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(310, 130, 54, 12))
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Default widget"))
        self.label.setText(_translate("Dialog", "Title"))
        self.label_2.setText(_translate("Dialog", "Author"))
        self.label_3.setText(_translate("Dialog", "Journal"))
        self.label_4.setText(_translate("Dialog", "URL"))
        self.label_5.setText(_translate("Dialog", "File"))
        self.pushButton.setText(_translate("Dialog", "Add Path"))
        self.label_6.setText(_translate("Dialog", "Year"))
