# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ludwig\Python Code\pyarticle_prj\ui\src\add_kwd.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 278)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(40, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.textedit_kwd = QtWidgets.QPlainTextEdit(Dialog)
        self.textedit_kwd.setGeometry(QtCore.QRect(20, 30, 361, 201))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.textedit_kwd.setFont(font)
        self.textedit_kwd.setStyleSheet("QPlainTextEdit {\n"
"    border: 1px solid#e6e6e6;\n"
"    background-color: white;\n"
"}")
        self.textedit_kwd.setObjectName("textedit_kwd")
        self.lb_key = QtWidgets.QLabel(Dialog)
        self.lb_key.setGeometry(QtCore.QRect(20, 10, 171, 16))
        self.lb_key.setObjectName("lb_key")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Keywords"))
        self.lb_key.setText(_translate("Dialog", "Add Keywords Line by Line"))
