# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets

from ui.modified import LTextEdit, LTextBrowser, SearchTextEdit
# QtWidgets.QPlainTextEdit = LPlainTextEdit
# QtWidgets.QTextBrowser = LTextBrowser

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1023, 680)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_search = QtWidgets.QPushButton(self.centralwidget)
        self.btn_search.setGeometry(QtCore.QRect(380, 50, 32, 32))
        self.btn_search.setStyleSheet("QPushButton {\n"
"    background-color: #E0E0E0;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D3D3D3;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #BEBEBE;\n"
"}\n"
"")
        self.btn_search.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_search.setIcon(icon)
        self.btn_search.setObjectName("btn_search")
        self.textedit_search = SearchTextEdit(self.centralwidget) # ludwig modified
        self.textedit_search.setEnabled(True)
        self.textedit_search.setGeometry(QtCore.QRect(30, 50, 341, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.textedit_search.setFont(font)
        self.textedit_search.setAcceptDrops(True)
        self.textedit_search.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textedit_search.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textedit_search.setObjectName("textedit_search")
        self.btn_import = QtWidgets.QPushButton(self.centralwidget)
        self.btn_import.setGeometry(QtCore.QRect(30, 10, 88, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_import.sizePolicy().hasHeightForWidth())
        self.btn_import.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.btn_import.setFont(font)
        self.btn_import.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_import.setAutoFillBackground(False)
        self.btn_import.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #397d3a;\n"
"}")
        self.btn_import.setObjectName("btn_import")
        self.btn_importb = QtWidgets.QPushButton(self.centralwidget)
        self.btn_importb.setGeometry(QtCore.QRect(130, 10, 88, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_importb.sizePolicy().hasHeightForWidth())
        self.btn_importb.setSizePolicy(sizePolicy)
        self.btn_importb.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_importb.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #397d3a;\n"
"}")
        self.btn_importb.setObjectName("btn_importb")
        self.btn_clear = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear.setGeometry(QtCore.QRect(380, 90, 32, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_clear.setFont(font)
        self.btn_clear.setStyleSheet("QPushButton {\n"
"    background-color: #E0E0E0;\n"
"    color: red;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D3D3D3;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #BEBEBE;\n"
"}\n"
"")
        self.btn_clear.setObjectName("btn_clear")
        self.btn_addman = QtWidgets.QPushButton(self.centralwidget)
        self.btn_addman.setGeometry(QtCore.QRect(230, 10, 88, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_addman.sizePolicy().hasHeightForWidth())
        self.btn_addman.setSizePolicy(sizePolicy)
        self.btn_addman.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_addman.setStyleSheet("QPushButton {\n"
"    background-color: #2196F3;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1E88E5;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1976D2;\n"
"}")
        self.btn_addman.setObjectName("btn_addman")
        self.btn_add_key = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_key.setGeometry(QtCore.QRect(330, 10, 88, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_add_key.sizePolicy().hasHeightForWidth())
        self.btn_add_key.setSizePolicy(sizePolicy)
        self.btn_add_key.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_add_key.setStyleSheet("QPushButton {\n"
"    background-color: #FF5722;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #F4511E;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #E64A19;\n"
"}\n"
"")
        self.btn_add_key.setObjectName("btn_add_key")
        self.btn_add_note = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_note.setGeometry(QtCore.QRect(430, 10, 88, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_add_note.sizePolicy().hasHeightForWidth())
        self.btn_add_note.setSizePolicy(sizePolicy)
        self.btn_add_note.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_add_note.setStyleSheet("QPushButton {\n"
"    background-color: #FF5722;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #F4511E;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #E64A19;\n"
"}\n"
"")
        self.btn_add_note.setObjectName("btn_add_note")
        self.btn_mdf = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mdf.setGeometry(QtCore.QRect(530, 10, 88, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_mdf.sizePolicy().hasHeightForWidth())
        self.btn_mdf.setSizePolicy(sizePolicy)
        self.btn_mdf.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_mdf.setStyleSheet("QPushButton {\n"
"    background-color: #9C27B0;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8E24AA;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #7B1FA2;\n"
"}")
        self.btn_mdf.setObjectName("btn_mdf")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(420, 50, 571, 571))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.browser_main = QtWidgets.QTextBrowser(self.page)
        self.browser_main.setGeometry(QtCore.QRect(0, 0, 571, 421))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.browser_main.setFont(font)
        self.browser_main.setObjectName("browser_main")
        self.browser_cmd = QtWidgets.QTextBrowser(self.page)
        self.browser_cmd.setGeometry(QtCore.QRect(0, 430, 571, 141))
        self.browser_cmd.setStyleSheet("QTextBrowser {\n"
"    background-color: black;\n"
"    color: white;\n"
"    font-family: Consolas, monospace;\n"
"}")
        self.browser_cmd.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.browser_cmd.setObjectName("browser_cmd")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.browser_info = LTextBrowser(self.page_2) # ludwig modified
        self.browser_info.setGeometry(QtCore.QRect(0, 0, 571, 201))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.browser_info.setFont(font)
        self.browser_info.setObjectName("browser_info")
        self.list_notes = QtWidgets.QListWidget(self.page_2)
        self.list_notes.setGeometry(QtCore.QRect(0, 310, 571, 261))
        self.list_notes.setObjectName("list_notes")
        self.browser_kwd = LTextBrowser(self.page_2) # ludwig modified
        self.browser_kwd.setGeometry(QtCore.QRect(0, 210, 571, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.browser_kwd.setFont(font)
        self.browser_kwd.setObjectName("browser_kwd")
        self.stackedWidget.addWidget(self.page_2)
        self.btn_download = QtWidgets.QPushButton(self.centralwidget)
        self.btn_download.setGeometry(QtCore.QRect(900, 10, 88, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_download.sizePolicy().hasHeightForWidth())
        self.btn_download.setSizePolicy(sizePolicy)
        self.btn_download.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_download.setStyleSheet("QPushButton {\n"
"    background-color: #5f5f5f;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4f4f4f;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3f3f3f;\n"
"}\n"
"")
        self.btn_download.setObjectName("btn_download")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(30, 40, 961, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 109, 381, 515))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_tree = QtWidgets.QWidget()
        self.tab_tree.setObjectName("tab_tree")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_tree)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tree_root = QtWidgets.QTreeWidget(self.tab_tree)
        self.tree_root.setHeaderHidden(True)
        self.tree_root.setObjectName("tree_root")
        self.tree_root.headerItem().setText(0, "1")
        self.tree_root.header().setVisible(False)
        self.verticalLayout_2.addWidget(self.tree_root)
        self.tabWidget.addTab(self.tab_tree, "")
        self.tab_search = QtWidgets.QWidget()
        self.tab_search.setObjectName("tab_search")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_search)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.list_searchs = QtWidgets.QListWidget(self.tab_search)
        self.list_searchs.setObjectName("list_searchs")
        self.verticalLayout.addWidget(self.list_searchs)
        self.tabWidget.addTab(self.tab_search, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.list_articles = QtWidgets.QListWidget(self.tab)
        self.list_articles.setObjectName("list_articles")
        self.verticalLayout_3.addWidget(self.list_articles)
        self.tabWidget.addTab(self.tab, "")
        self.btn_sync = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sync.setGeometry(QtCore.QRect(840, 10, 25, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_sync.sizePolicy().hasHeightForWidth())
        self.btn_sync.setSizePolicy(sizePolicy)
        self.btn_sync.setStyleSheet("QPushButton {\n"
"    background-color: #E0E0E0;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D3D3D3;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #BEBEBE;\n"
"}\n"
"")
        self.btn_sync.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/synchron_blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_sync.setIcon(icon1)
        self.btn_sync.setObjectName("btn_sync")
        self.btn_sync_r = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sync_r.setGeometry(QtCore.QRect(870, 10, 25, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_sync_r.sizePolicy().hasHeightForWidth())
        self.btn_sync_r.setSizePolicy(sizePolicy)
        self.btn_sync_r.setStyleSheet("QPushButton {\n"
"    background-color: #E0E0E0;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D3D3D3;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #BEBEBE;\n"
"}\n"
"")
        self.btn_sync_r.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/synchron_red.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_sync_r.setIcon(icon2)
        self.btn_sync_r.setObjectName("btn_sync_r")
        self.btn_search.raise_()
        self.textedit_search.raise_()
        self.btn_import.raise_()
        self.btn_importb.raise_()
        self.btn_addman.raise_()
        self.btn_add_key.raise_()
        self.btn_add_note.raise_()
        self.btn_mdf.raise_()
        self.stackedWidget.raise_()
        self.btn_download.raise_()
        self.line.raise_()
        self.tabWidget.raise_()
        self.btn_clear.raise_()
        self.btn_sync.raise_()
        self.btn_sync_r.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1023, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setMouseTracking(False)
        self.statusbar.setTabletTracking(True)
        self.statusbar.setAutoFillBackground(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textedit_search.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">input the text</p></body></html>"))
        self.btn_import.setText(_translate("MainWindow", "Import Paper"))
        self.btn_importb.setText(_translate("MainWindow", "Import Batch"))
        self.btn_clear.setText(_translate("MainWindow", "C"))
        self.btn_addman.setText(_translate("MainWindow", "Add Manually"))
        self.btn_add_key.setText(_translate("MainWindow", "Add Keywords"))
        self.btn_add_note.setText(_translate("MainWindow", "Add Notes"))
        self.btn_mdf.setText(_translate("MainWindow", "Modified"))
        self.browser_cmd.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\',\'monospace\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btn_download.setText(_translate("MainWindow", "Download"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tree), _translate("MainWindow", "Tree View"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_search), _translate("MainWindow", "Search Page"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Repository"))
import ui.res_rc
